# app/config/fos/config.yml
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: BackendBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
