fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /adminSonata

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /adminPanel

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /back

    
