<?php
namespace BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComplaintsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplaintsRepository extends EntityRepository
{
    
}
