<?php

namespace Proxies\__CG__\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ContactForm extends \BackendBundle\Entity\ContactForm implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'fromName', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'fromEmail', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'fromPhone', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'subject', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'message', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'dateadd', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'viewed');
        }

        return array('__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'fromName', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'fromEmail', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'fromPhone', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'subject', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'message', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'dateadd', '' . "\0" . 'BackendBundle\\Entity\\ContactForm' . "\0" . 'viewed');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ContactForm $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromName($fromName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromName', array($fromName));

        return parent::setFromName($fromName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromName', array());

        return parent::getFromName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromEmail($fromEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromEmail', array($fromEmail));

        return parent::setFromEmail($fromEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromEmail', array());

        return parent::getFromEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromPhone($fromPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromPhone', array($fromPhone));

        return parent::setFromPhone($fromPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromPhone', array());

        return parent::getFromPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject($subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', array($subject));

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', array());

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', array($message));

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', array());

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateadd($dateadd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateadd', array($dateadd));

        return parent::setDateadd($dateadd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateadd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateadd', array());

        return parent::getDateadd();
    }

    /**
     * {@inheritDoc}
     */
    public function setViewed($viewed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViewed', array($viewed));

        return parent::setViewed($viewed);
    }

    /**
     * {@inheritDoc}
     */
    public function getViewed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViewed', array());

        return parent::getViewed();
    }

}
