<?php

namespace Proxies\__CG__\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bookings extends \BackendBundle\Entity\Bookings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerName', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerLastname', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerPhone', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerEmail', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'productReference', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'productAddress', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'checkin', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'checkout', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'nights', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'priceNight', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'priceTotal', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'anfitrionFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookDate', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookIp', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookConfirmed', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'pax', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookPayed', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'paymentType', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'paypalFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'useranfitrion', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'product', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'usercustomer'];
        }

        return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerName', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerLastname', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerPhone', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerEmail', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'productReference', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'productAddress', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'checkin', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'checkout', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'nights', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'priceNight', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'priceTotal', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'anfitrionFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookDate', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookIp', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookConfirmed', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'pax', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookPayed', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'paymentType', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'paypalFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'useranfitrion', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'product', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'usercustomer'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bookings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerName($customerName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerName', [$customerName]);

        return parent::setCustomerName($customerName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerName', []);

        return parent::getCustomerName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerLastname($customerLastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerLastname', [$customerLastname]);

        return parent::setCustomerLastname($customerLastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerLastname', []);

        return parent::getCustomerLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerPhone($customerPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerPhone', [$customerPhone]);

        return parent::setCustomerPhone($customerPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerPhone', []);

        return parent::getCustomerPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerEmail($customerEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerEmail', [$customerEmail]);

        return parent::setCustomerEmail($customerEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerEmail', []);

        return parent::getCustomerEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductReference($productReference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductReference', [$productReference]);

        return parent::setProductReference($productReference);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductReference', []);

        return parent::getProductReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductAddress($productAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductAddress', [$productAddress]);

        return parent::setProductAddress($productAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductAddress', []);

        return parent::getProductAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckin($checkin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckin', [$checkin]);

        return parent::setCheckin($checkin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckin', []);

        return parent::getCheckin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckout($checkout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckout', [$checkout]);

        return parent::setCheckout($checkout);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckout', []);

        return parent::getCheckout();
    }

    /**
     * {@inheritDoc}
     */
    public function setNights($nights)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNights', [$nights]);

        return parent::setNights($nights);
    }

    /**
     * {@inheritDoc}
     */
    public function getNights()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNights', []);

        return parent::getNights();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceNight($priceNight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceNight', [$priceNight]);

        return parent::setPriceNight($priceNight);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceNight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceNight', []);

        return parent::getPriceNight();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceTotal($priceTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceTotal', [$priceTotal]);

        return parent::setPriceTotal($priceTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceTotal', []);

        return parent::getPriceTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerFee($customerFee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerFee', [$customerFee]);

        return parent::setCustomerFee($customerFee);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerFee', []);

        return parent::getCustomerFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnfitrionFee($anfitrionFee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnfitrionFee', [$anfitrionFee]);

        return parent::setAnfitrionFee($anfitrionFee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnfitrionFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnfitrionFee', []);

        return parent::getAnfitrionFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserName($userName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserName', [$userName]);

        return parent::setUserName($userName);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserName', []);

        return parent::getUserName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserEmail($userEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserEmail', [$userEmail]);

        return parent::setUserEmail($userEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserEmail', []);

        return parent::getUserEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPhone($userPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPhone', [$userPhone]);

        return parent::setUserPhone($userPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPhone', []);

        return parent::getUserPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookDate($bookDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookDate', [$bookDate]);

        return parent::setBookDate($bookDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookDate', []);

        return parent::getBookDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookIp($bookIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookIp', [$bookIp]);

        return parent::setBookIp($bookIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookIp', []);

        return parent::getBookIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookConfirmed($bookConfirmed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookConfirmed', [$bookConfirmed]);

        return parent::setBookConfirmed($bookConfirmed);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookConfirmed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookConfirmed', []);

        return parent::getBookConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPax($pax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPax', [$pax]);

        return parent::setPax($pax);
    }

    /**
     * {@inheritDoc}
     */
    public function getPax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPax', []);

        return parent::getPax();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookPayed($bookPayed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookPayed', [$bookPayed]);

        return parent::setBookPayed($bookPayed);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookPayed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookPayed', []);

        return parent::getBookPayed();
    }

    /**
     * {@inheritDoc}
     */
    public function setUseranfitrion(\BackendBundle\Entity\User $useranfitrion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUseranfitrion', [$useranfitrion]);

        return parent::setUseranfitrion($useranfitrion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUseranfitrion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUseranfitrion', []);

        return parent::getUseranfitrion();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\BackendBundle\Entity\Products $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', [$product]);

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', []);

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsercustomer(\BackendBundle\Entity\User $usercustomer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsercustomer', [$usercustomer]);

        return parent::setUsercustomer($usercustomer);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsercustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsercustomer', []);

        return parent::getUsercustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentType($paymentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentType', [$paymentType]);

        return parent::setPaymentType($paymentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentType', []);

        return parent::getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaypalFee($paypalFee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaypalFee', [$paypalFee]);

        return parent::setPaypalFee($paypalFee);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaypalFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaypalFee', []);

        return parent::getPaypalFee();
    }

}
