<?php

namespace Proxies\__CG__\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bookings extends \BackendBundle\Entity\Bookings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerName', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerLastname', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerPhone', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerEmail', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'productReference', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'productAddress', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'checkin', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'checkout', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'nights', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'priceNight', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'priceTotal', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'anfitrionFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookDate', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookIp', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookConfirmed', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'pax', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookPayed', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'paymentType', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'paypalFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'useranfitrion', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'product', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'usercustomer');
        }

        return array('__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerName', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerLastname', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerPhone', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerEmail', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'productReference', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'productAddress', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'checkin', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'checkout', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'nights', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'priceNight', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'priceTotal', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'customerFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'anfitrionFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookDate', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookIp', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookConfirmed', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'pax', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'bookPayed', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'paymentType', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'paypalFee', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'useranfitrion', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'product', '' . "\0" . 'BackendBundle\\Entity\\Bookings' . "\0" . 'usercustomer');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bookings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerName($customerName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerName', array($customerName));

        return parent::setCustomerName($customerName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerName', array());

        return parent::getCustomerName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerLastname($customerLastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerLastname', array($customerLastname));

        return parent::setCustomerLastname($customerLastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerLastname', array());

        return parent::getCustomerLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerPhone($customerPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerPhone', array($customerPhone));

        return parent::setCustomerPhone($customerPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerPhone', array());

        return parent::getCustomerPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerEmail($customerEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerEmail', array($customerEmail));

        return parent::setCustomerEmail($customerEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerEmail', array());

        return parent::getCustomerEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductReference($productReference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductReference', array($productReference));

        return parent::setProductReference($productReference);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductReference', array());

        return parent::getProductReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductAddress($productAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductAddress', array($productAddress));

        return parent::setProductAddress($productAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductAddress', array());

        return parent::getProductAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckin($checkin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckin', array($checkin));

        return parent::setCheckin($checkin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckin', array());

        return parent::getCheckin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckout($checkout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckout', array($checkout));

        return parent::setCheckout($checkout);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckout', array());

        return parent::getCheckout();
    }

    /**
     * {@inheritDoc}
     */
    public function setNights($nights)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNights', array($nights));

        return parent::setNights($nights);
    }

    /**
     * {@inheritDoc}
     */
    public function getNights()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNights', array());

        return parent::getNights();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceNight($priceNight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceNight', array($priceNight));

        return parent::setPriceNight($priceNight);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceNight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceNight', array());

        return parent::getPriceNight();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceTotal($priceTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceTotal', array($priceTotal));

        return parent::setPriceTotal($priceTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceTotal', array());

        return parent::getPriceTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerFee($customerFee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerFee', array($customerFee));

        return parent::setCustomerFee($customerFee);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerFee', array());

        return parent::getCustomerFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnfitrionFee($anfitrionFee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnfitrionFee', array($anfitrionFee));

        return parent::setAnfitrionFee($anfitrionFee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnfitrionFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnfitrionFee', array());

        return parent::getAnfitrionFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserName($userName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserName', array($userName));

        return parent::setUserName($userName);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserName', array());

        return parent::getUserName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserEmail($userEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserEmail', array($userEmail));

        return parent::setUserEmail($userEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserEmail', array());

        return parent::getUserEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPhone($userPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPhone', array($userPhone));

        return parent::setUserPhone($userPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPhone', array());

        return parent::getUserPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookDate($bookDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookDate', array($bookDate));

        return parent::setBookDate($bookDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookDate', array());

        return parent::getBookDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookIp($bookIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookIp', array($bookIp));

        return parent::setBookIp($bookIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookIp', array());

        return parent::getBookIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookConfirmed($bookConfirmed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookConfirmed', array($bookConfirmed));

        return parent::setBookConfirmed($bookConfirmed);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookConfirmed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookConfirmed', array());

        return parent::getBookConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPax($pax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPax', array($pax));

        return parent::setPax($pax);
    }

    /**
     * {@inheritDoc}
     */
    public function getPax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPax', array());

        return parent::getPax();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookPayed($bookPayed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookPayed', array($bookPayed));

        return parent::setBookPayed($bookPayed);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookPayed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookPayed', array());

        return parent::getBookPayed();
    }

    /**
     * {@inheritDoc}
     */
    public function setUseranfitrion(\BackendBundle\Entity\User $useranfitrion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUseranfitrion', array($useranfitrion));

        return parent::setUseranfitrion($useranfitrion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUseranfitrion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUseranfitrion', array());

        return parent::getUseranfitrion();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\BackendBundle\Entity\Products $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', array($product));

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', array());

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsercustomer(\BackendBundle\Entity\User $usercustomer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsercustomer', array($usercustomer));

        return parent::setUsercustomer($usercustomer);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsercustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsercustomer', array());

        return parent::getUsercustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentType($paymentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentType', array($paymentType));

        return parent::setPaymentType($paymentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentType', array());

        return parent::getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaypalFee($paypalFee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaypalFee', array($paypalFee));

        return parent::setPaypalFee($paypalFee);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaypalFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaypalFee', array());

        return parent::getPaypalFee();
    }

}
