backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }
    
backend_user_list:
    path:     /user/list
    defaults: { _controller: BackendBundle:Default:index }

calculate_room_price:
    path: /room/calculate/price/{id}
    defaults: { _controller: BackendBundle:Rooms:calculatePrice }